### ISSUE TITLE
0.24版本参照教程无法启动schedule

### ISSUE THREAD

**Issue by zhyueyueniao** [liuli-io/liuli#69]
如果按照教程手动添加pro.env**文件**，无法启动docker，但是如果不手动添加文件，启动docker的话会自动创建pro.env**文件夹**，然后docker会循环输出如下日志
Loading .env environment variables...
Start schedule(pro) serve: PIPENV_DOTENV_LOCATION=./pro.env pipenv run python src/liuli_schedule.py
Warning: file PIPENV_DOTENV_LOCATION=./pro.env does not exist!!
Not loading environment variables.
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/code/src/liuli_schedule.py", line 84, in run_liuli_schedule
    ll_config = json.load(load_f)
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

**Comment by howie6879** [comment]
@zhyueyueniao 

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/17047388/203513196-15c8b8a1-34bd-40b0-8579-2ca7a63001c7.png">


ni'xu'yc你需要配置这两个文件
